Repository Mojtabarezaei4/Queueomatic, pull requests merged in 2023-05, with the labels that each got.

#32 Update dotnetSecond.yml
  .github/workflows/dotnetSecond.yml
Labels: enhancement

#38 Create data access project
  Queueomatic/Queueomatic.DataAccess/Queueomatic.DataAccess.csproj
  Queueomatic/Queueomatic.sln
Labels: enhancement

#39 Add support for fep
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Queueomatic.Server.csproj
Labels: enhancement

#40 Create data context
  Queueomatic/Queueomatic.DataAccess/DataContexts/AppContext.cs
  Queueomatic/Queueomatic.DataAccess/Queueomatic.DataAccess.csproj
Labels: enhancement

#41 Add Unit of Work
  Queueomatic/Queueomatic.DataAccess/DataContexts/AppContext.cs
  Queueomatic/Queueomatic.DataAccess/DataContexts/ApplicationContext.cs
  Queueomatic/Queueomatic.DataAccess/Queueomatic.DataAccess.csproj
  Queueomatic/Queueomatic.DataAccess/UnitOfWork/IUnitOfWork.cs
  Queueomatic/Queueomatic.DataAccess/UnitOfWork/UnitOfWork.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Queueomatic.Server.csproj
Labels: enhancement

#44 Add hashids
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Queueomatic.Server.csproj
Labels: documentation, enhancement

#43 Create repositories
  Queueomatic/Queueomatic.DataAccess/DataContexts/ApplicationContext.cs
  Queueomatic/Queueomatic.DataAccess/Migrations/20230506121006_Base Migration.Designer.cs
  Queueomatic/Queueomatic.DataAccess/Migrations/20230506121006_Base Migration.cs
  Queueomatic/Queueomatic.DataAccess/Migrations/ApplicationContextModelSnapshot.cs
  Queueomatic/Queueomatic.DataAccess/Models/Room.cs
  Queueomatic/Queueomatic.DataAccess/Queueomatic.DataAccess.csproj
  Queueomatic/Queueomatic.DataAccess/Repositories/Interfaces/IRepository.cs
  Queueomatic/Queueomatic.DataAccess/Repositories/Interfaces/IRoomRepository.cs
  Queueomatic/Queueomatic.DataAccess/Repositories/Interfaces/IUserRepository.cs
  Queueomatic/Queueomatic.DataAccess/Repositories/RoomRepository.cs
  Queueomatic/Queueomatic.DataAccess/Repositories/UserRepository.cs
  Queueomatic/Queueomatic.DataAccess/UnitOfWork/IUnitOfWork.cs
  Queueomatic/Queueomatic.DataAccess/UnitOfWork/UnitOfWork.cs
  Queueomatic/Queueomatic.Test/Queueomatic.Test.csproj
  Queueomatic/Queueomatic.Test/RoomRepository_ReturnCorrectValues.cs
  Queueomatic/Queueomatic.Test/UnitTest1.cs
  Queueomatic/Queueomatic.Test/UserRepository_ReturnCorrectValues.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Queueomatic.Server.csproj
  Queueomatic/Server/appsettings.json
Labels: enhancement

#49 Create authorization service
  Queueomatic/Server/Program.cs
Labels: enhancement

#51 Create authentication service
  Queueomatic/Queueomatic.Test/AuthenticationService_VerifySequence.cs
  Queueomatic/Queueomatic.Test/Queueomatic.Test.csproj
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Services/AuthenticationService/AuthenticationService.cs
  Queueomatic/Server/Services/AuthenticationService/IAuthenticationService.cs
Labels: documentation, enhancement

#74 Create hash id service
  Queueomatic/Queueomatic.Test/HashIdService_Tests.cs
  Queueomatic/Server/Queueomatic.Server.csproj
  Queueomatic/Server/Services/HashIdService/HashIdService.cs
  Queueomatic/Server/Services/HashIdService/IHashIdService.cs
  Queueomatic/Server/appsettings.json
Labels: enhancement

#73 Implement add new room endpoint
  Queueomatic/Queueomatic.Test/CreateRoomService_ReturnCorrectValue.cs
  Queueomatic/Server/Endpoints/Room/Add/AddNewRoomEndpoint.cs
  Queueomatic/Server/Endpoints/Room/Add/AddNewRoomRequest.cs
  Queueomatic/Server/Endpoints/Room/Add/AddNewRoomValidator.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Services/CreateRoomService/CreateRoomService.cs
  Queueomatic/Server/Services/CreateRoomService/ICreateRoomService.cs
  Queueomatic/Shared/Resources/Adjectives.cs
  Queueomatic/Shared/Resources/Nouns.cs
Labels: enhancement

#77 Create room service
  Queueomatic/Queueomatic.Test/CreateRoomService_ReturnCorrectValue.cs
  Queueomatic/Queueomatic.Test/RoomService_Tests.cs
  Queueomatic/Server/Endpoints/Room/Add/AddNewRoomEndpoint.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Services/CreateRoomService/CreateRoomService.cs
  Queueomatic/Server/Services/CreateRoomService/ICreateRoomService.cs
  Queueomatic/Server/Services/HashIdService/HashIdService.cs
  Queueomatic/Server/Services/RoomService/IRoomService.cs
  Queueomatic/Server/Services/RoomService/RoomService.cs
Labels: documentation, enhancement

#78 Update room service
  Queueomatic/Queueomatic.Test/RoomService_Tests.cs
  Queueomatic/Server/Services/RoomService/IRoomService.cs
  Queueomatic/Server/Services/RoomService/RoomService.cs
Labels: documentation, enhancement

#79 Implement get user by email
  Queueomatic/Queueomatic.DataAccess/Repositories/UserRepository.cs
  Queueomatic/Queueomatic.Test/CreateRoomService_ReturnCorrectValue.cs
  Queueomatic/Server/Endpoints/Room/Add/AddNewRoomEndpoint.cs
  Queueomatic/Server/Endpoints/Room/Add/AddNewRoomRequest.cs
  Queueomatic/Server/Endpoints/Room/Add/AddNewRoomValidator.cs
  Queueomatic/Server/Endpoints/User/GetByEmail/GetUserByEmailEndpoint.cs
  Queueomatic/Server/Endpoints/User/GetByEmail/GetUserByEmailRequest.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Services/RoomService/IRoomService.cs
  Queueomatic/Server/Services/RoomService/RoomService.cs
Labels: documentation, enhancement

#81 Create get rooms endpoint
  Queueomatic/Queueomatic.DataAccess/Repositories/Interfaces/IRoomRepository.cs
  Queueomatic/Queueomatic.DataAccess/Repositories/RoomRepository.cs
  Queueomatic/Queueomatic.Test/HashIdService_Tests.cs
  Queueomatic/Server/Endpoints/Room/GetAll/GetAllRoomEndpoint.cs
  Queueomatic/Server/Endpoints/Room/GetAll/GetAllRoomRequest.cs
  Queueomatic/Server/Endpoints/Room/GetAll/GetAllRoomsEndpoint.cs
  Queueomatic/Server/Endpoints/Room/GetAll/GetAllRoomsResponse.cs
  Queueomatic/Server/Services/HashIdService/HashIdService.cs
Labels: documentation, enhancement

#91 Create nav bar
  Queueomatic/Client/App.razor
  Queueomatic/Client/CustomAuthenticationStateProvider.cs
  Queueomatic/Client/Pages/Index.razor
  Queueomatic/Client/Program.cs
  Queueomatic/Client/Queueomatic.Client.csproj
  Queueomatic/Client/Shared/MainLayout.razor
  Queueomatic/Client/Shared/NavMenu.razor
  Queueomatic/Client/Shared/NavMenu.razor.css
  Queueomatic/Client/_Imports.razor
  Queueomatic/Client/wwwroot/static/logo.png
Labels: documentation, enhancement

#98 Feat: Add impelementaion of add new participant endpoint
  Queueomatic/Queueomatic.Test/ParticipantService_AddParticipant.cs
  Queueomatic/Server/Endpoints/Participant/Add/AddNewParticipantEndpoint.cs
  Queueomatic/Server/Endpoints/Participant/Add/AddNewParticipantResponse.cs
  Queueomatic/Server/Endpoints/Participant/Add/AddNewParticipantValidator.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Services/ParticipantService/IParticipantService.cs
  Queueomatic/Server/Services/ParticipantService/ParticipantService.cs
Labels: enhancement

#99 Implement edit participant endpoint
  Queueomatic/Queueomatic.Test/ParticipantService_AddParticipant.cs
  Queueomatic/Server/Endpoints/Participant/Edit/EditParticipantEndpoint.cs
  Queueomatic/Server/Endpoints/Participant/Edit/EditParticipantRequest.cs
  Queueomatic/Server/Endpoints/Participant/Edit/EditParticipantResponse.cs
  Queueomatic/Server/Services/ParticipantService/IParticipantService.cs
  Queueomatic/Server/Services/ParticipantService/ParticipantService.cs
Labels: enhancement

#101 More test cases adding participant service
  Queueomatic/Queueomatic.Test/ParticipantService_AddParticipant.cs
Labels: enhancement

#103 Add SignalR
  Queueomatic/Client/Queueomatic.Client.csproj
  Queueomatic/Server/Program.cs
Labels: enhancement

#106 Add loading animation
  Queueomatic/Client/wwwroot/css/app.css
  Queueomatic/Client/wwwroot/index.html
Labels: enhancement, UI

#107 Implement delete participant endpoint
  Queueomatic/Server/Endpoints/Participant/Delete/DeleteParticipantEndpoint.cs
  Queueomatic/Server/Endpoints/Participant/Delete/DeleteParticipantRequest.cs
  Queueomatic/Server/Endpoints/Participant/Delete/DeleteParticipantResponse.cs
  Queueomatic/Server/Endpoints/Participant/Delete/DeleteParticipantValidator.cs
  Queueomatic/Server/Services/ParticipantService/IParticipantService.cs
  Queueomatic/Server/Services/ParticipantService/ParticipantService.cs
Labels: enhancement, Server/API

#109 Create landing page
  Queueomatic/Client/Pages/Index.razor
  Queueomatic/Client/Pages/Index.razor.css
  Queueomatic/Client/Shared/MainLayout.razor
  Queueomatic/Client/Shared/MainLayout.razor.css
  Queueomatic/Client/Shared/NavMenu.razor
  Queueomatic/Client/wwwroot/static/Icon.png
  Queueomatic/Client/wwwroot/static/moonrising.ttf
Labels: UI

#112 Create login page
  Queueomatic/Client/Components/Login/LoginComponent.razor
  Queueomatic/Client/Components/Login/LoginComponent.razor.cs
  Queueomatic/Client/Components/Login/LoginComponent.razor.css
  Queueomatic/Client/Components/Logo/LogoComponent.razor
  Queueomatic/Client/Components/Logo/LogoComponent.razor.css
  Queueomatic/Client/Components/RedirectHome.razor
  Queueomatic/Client/Pages/Index.razor
  Queueomatic/Client/Pages/Login.razor
  Queueomatic/Client/Shared/NavMenu.razor
  Queueomatic/Client/_Imports.razor
Labels: enhancement, UI

#114 Create sign up page
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor.cs
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor.css
  Queueomatic/Client/Pages/Login.razor
  Queueomatic/Client/Pages/SignUp.razor
  Queueomatic/Client/_Imports.razor
  Queueomatic/Shared/DTOs/SignupDto.cs
Labels: enhancement, UI
