Repository Mojtabarezaei4/Queueomatic, pull requests merged in 2023-06, with the labels that each got.

#119 Bug: Prevent login button from multi click
  Queueomatic/Client/Components/Login/LoginComponent.razor
  Queueomatic/Client/Components/Login/LoginComponent.razor.cs
  Queueomatic/Client/Components/Login/LoginComponent.razor.css
Labels: bug, UI

#117 Create room page
  Queueomatic/Client/Pages/Room.razor
  Queueomatic/Client/Pages/Room.razor.cs
  Queueomatic/Client/Pages/Room.razor.css
  Queueomatic/Client/Program.cs
  Queueomatic/Client/Queueomatic.Client.csproj
  Queueomatic/Client/_Imports.razor
  Queueomatic/Queueomatic.sln
Labels: enhancement, UI

#121 Feat: Add error page
  Queueomatic/Client/App.razor
  Queueomatic/Client/Components/Error/ErrorComponent.razor
  Queueomatic/Client/Components/Error/ErrorComponent.razor.css
  Queueomatic/Client/Pages/Error.razor
  Queueomatic/Client/Shared/MainLayout.razor
  Queueomatic/Client/_Imports.razor
Labels: enhancement, UI

#123 Style: Restyle the content of signup-button to its status
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor.cs
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor.css
Labels: UI

#124 Create profile page
  Queueomatic/Client/Components/Profile/ProfileComponent.razor
  Queueomatic/Client/Components/Profile/ProfileComponent.razor.cs
  Queueomatic/Client/Components/Profile/ProfileComponent.razor.css
  Queueomatic/Client/CustomAuthenticationStateProvider.cs
  Queueomatic/Client/Pages/Profile.razor
  Queueomatic/Client/Shared/NavMenu.razor
  Queueomatic/Client/Shared/NavMenu.razor.css
  Queueomatic/Client/_Imports.razor
  Queueomatic/Client/wwwroot/avatar.png
  Queueomatic/Client/wwwroot/static/Icon.png
Labels: enhancement, UI

#132 Handle signup scenario where a user already exists
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor.cs
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor.css
  Queueomatic/Client/Queueomatic.Client.csproj
  Queueomatic/Server/Endpoints/ForgetPassword/ForgetPasswordEndpoint.cs
  Queueomatic/Server/Endpoints/ResetPassword/ResetPasswordEndpoint.cs
Labels: bug, invalid, UI, Server/API

#133 Feat: Add auto deletion for the expired rooms
  Queueomatic/Queueomatic.DataAccess/Repositories/Interfaces/IRoomRepository.cs
  Queueomatic/Queueomatic.DataAccess/Repositories/RoomRepository.cs
  Queueomatic/Server/BackgroundServices/ScopedBackgroundService.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Services/RoomDeletionService/IRoomDeletionService.cs
  Queueomatic/Server/Services/RoomDeletionService/RoomDeletionService.cs
Labels: enhancement, Server/API

#136 Feat: Add logout function
  Queueomatic/Client/Pages/Logout.razor
  Queueomatic/Client/Pages/Logout.razor.cs
  Queueomatic/Client/Pages/Logout.razor.css
  Queueomatic/Client/Shared/NavMenu.razor
  Queueomatic/Client/Shared/NavMenu.razor.css
Labels: enhancement, UI

#138 Style: Change the response message from just a text to a toast
  Queueomatic/Client/Components/Login/LoginComponent.razor
  Queueomatic/Client/Components/Login/LoginComponent.razor.cs
Labels: UI

#139 Style: Change the favicon to the Logo and also add propper page title
  Queueomatic/Client/Pages/Index.razor
  Queueomatic/Client/Pages/Login.razor
  Queueomatic/Client/Pages/Logout.razor
  Queueomatic/Client/Pages/Profile.razor
  Queueomatic/Client/Pages/Room.razor
  Queueomatic/Client/Pages/SignUp.razor
  Queueomatic/Client/wwwroot/favicon.png
Labels: bug, good first issue, UI

#143 Implement signal r client server
  Queueomatic/Client/Pages/Room.razor
  Queueomatic/Client/Pages/Room.razor.cs
  Queueomatic/Client/Pages/Room.razor.css
  Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Shared/DTOs/ParticipantRoomDto.cs
Labels: enhancement, UI, Server/API

#149 Change the modal on profile page to a blazoredmodal
  Queueomatic/Client/App.razor
  Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor
  Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor.cs
  Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor.css
  Queueomatic/Client/Components/Login/LoginComponent.razor
  Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor
  Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor.cs
  Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor.css
  Queueomatic/Client/Components/Profile/ProfileComponent.razor
  Queueomatic/Client/Components/Profile/ProfileComponent.razor.cs
  Queueomatic/Client/Pages/Index.razor
  Queueomatic/Client/Pages/Index.razor.cs
  Queueomatic/Client/Pages/Index.razor.css
  Queueomatic/Client/Program.cs
  Queueomatic/Client/Queueomatic.Client.csproj
  Queueomatic/Client/_Imports.razor
  Queueomatic/Client/wwwroot/css/app.css
Labels: bug, UI
