Repository Mojtabarezaei4/Queueomatic, pull requests merged in 2024-01, with the labels that each got.

#165 Add UI and functionality to create a room
  Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor
  Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor.cs
  Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor.css
  Queueomatic/Client/Pages/Room.razor.cs
  Queueomatic/Client/Queueomatic.Client.csproj
  Queueomatic/Client/Shared/NavMenu.razor
  Queueomatic/Client/_Imports.razor
  Queueomatic/Queueomatic.Test/CreateRoomService_ReturnCorrectValue.cs
  Queueomatic/Server/Endpoints/Room/Add/AddNewRoomEndpoint.cs
  Queueomatic/Server/Endpoints/Room/Add/AddNewRoomResponse.cs
  Queueomatic/Server/Services/CacheRoomService/CacheRoomService.cs
  Queueomatic/Server/Services/RoomService/IRoomService.cs
  Queueomatic/Server/Services/RoomService/RoomService.cs
Labels: UI

#169 Migrate signal r interfaces
  Queueomatic/Client/Pages/Room.razor.cs
  Queueomatic/Server/Endpoints/Hubs/Room/IRoomClient.cs
  Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs
Labels: Server/API

#172 Display recently joined rooms on the home page
  Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor
  Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor.cs
  Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor
  Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor.cs
  Queueomatic/Client/Components/Profile/ProfileComponent.razor
  Queueomatic/Client/Components/Profile/ProfileComponent.razor.cs
  Queueomatic/Client/Components/VisitedRooms/VisitedRoomsComponent.razor
  Queueomatic/Client/Components/VisitedRooms/VisitedRoomsComponent.razor.cs
  Queueomatic/Client/Components/VisitedRooms/VisitedRoomsComponent.razor.css
  Queueomatic/Client/Pages/Index.razor
  Queueomatic/Client/Pages/Index.razor.cs
  Queueomatic/Client/Pages/Index.razor.css
  Queueomatic/Client/Pages/Room.razor
  Queueomatic/Client/Pages/Room.razor.cs
  Queueomatic/Client/Program.cs
  Queueomatic/Client/Queueomatic.Client.csproj
  Queueomatic/Client/Services/ManageVisitedRooms/IManageVisitedRooms.cs
  Queueomatic/Client/Services/ManageVisitedRooms/ManageVisitedRooms.cs
  Queueomatic/Client/Shared/NavMenu.razor
  Queueomatic/Client/_Imports.razor
Labels: UI

#175 Show room id for owner of the room in the room page
  Queueomatic/Client/Pages/Room.razor
  Queueomatic/Client/Pages/Room.razor.cs
  Queueomatic/Client/Pages/Room.razor.css
Labels: UI

#176 Filter logging
  Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor.cs
  Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor
  Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor.cs
  Queueomatic/Client/Components/Login/LoginComponent.razor.cs
  Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor.cs
  Queueomatic/Client/Components/Profile/ProfileComponent.razor
  Queueomatic/Client/Components/Profile/ProfileComponent.razor.cs
  Queueomatic/Client/Components/Profile/ProfileComponent.razor.css
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor
  Queueomatic/Client/Components/SignUp/SignUpComponent.razor.cs
  Queueomatic/Client/Components/VisitedRooms/VisitedRoomsComponent.razor.cs
  Queueomatic/Client/Components/VisitedRooms/VisitedRoomsComponent.razor.css
  Queueomatic/Client/CustomAuthenticationStateProvider.cs
  Queueomatic/Client/Pages/Index.razor.cs
  Queueomatic/Client/Pages/Room.razor
  Queueomatic/Client/Pages/Room.razor.cs
  Queueomatic/Client/Shared/NavMenu.razor
  Queueomatic/Queueomatic.Test/AuthenticationServiceTests.cs
  Queueomatic/Queueomatic.Test/CreateRoomService_ReturnCorrectValue.cs
  Queueomatic/Queueomatic.Test/HashIdServiceTests.cs
  Queueomatic/Queueomatic.Test/ParticipantServiceTests.cs
  Queueomatic/Queueomatic.Test/ParticipantService_AddParticipant.cs
  Queueomatic/Queueomatic.Test/Queueomatic.Test.csproj
  Queueomatic/Queueomatic.Test/RoomRepositoryTests.cs
  Queueomatic/Queueomatic.Test/RoomServiceTests.cs
  Queueomatic/Queueomatic.Test/RoomService_Tests.cs
  Queueomatic/Queueomatic.Test/UserRepositoryTests.cs
  Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs
  Queueomatic/Server/Endpoints/Participant/Delete/DeleteParticipantEndpoint.cs
  Queueomatic/Server/Endpoints/Participant/Delete/DeleteParticipantRequest.cs
  Queueomatic/Server/Endpoints/Participant/Edit/EditParticipantRequest.cs
  Queueomatic/Server/Endpoints/ResetPassword/ResetPasswordEndpoint.cs
  Queueomatic/Server/Endpoints/Room/GetById/GetRoomByIdEndpoint.cs
  Queueomatic/Server/Endpoints/User/ChangeUsername/ChangeUsernameRequest.cs
  Queueomatic/Server/Endpoints/User/Delete/DeleteUserEndpoint.cs
  Queueomatic/Server/Endpoints/User/Edit/EditUserEndpoint.cs
  Queueomatic/Server/Handlers/RoomRestrictionAuthorization/RoomRestrictionRequirementHandler.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Server/Services/CacheRoomService/CacheRoomService.cs
  Queueomatic/Server/Services/CacheRoomService/ICacheRoomService.cs
  Queueomatic/Server/Services/ParticipantService/ParticipantService.cs
  Queueomatic/Server/appsettings.json
  Queueomatic/Shared/DTOs/ResetPasswordDto.cs
Labels: UI, Server/API

#182 Add db initializer
  Queueomatic/Queueomatic.DataAccess/DataContexts/ApplicationContext.cs
  Queueomatic/Server/Program.cs
  Queueomatic/Server/appsettings.json
Labels: bug, Server/API

#183 Added table initializer
  Queueomatic/Queueomatic.DataAccess/DataContexts/ApplicationContext.cs
Labels: Release :rocket:
